const units = [
    {name: '个', nameEn: 'PC'},
    {name: '把', nameEn: 'PC'},
    {name: '只', nameEn: 'PC'},
    {name: '支', nameEn: 'PC'},
    {name: '打', nameEn: 'DOZ'},
    {name: '套', nameEn: 'SET'},
    {name: '片', nameEn: 'PC'},
    {name: '令', nameEn: 'REAM'},
    {name: '卷', nameEn: 'ROLL'},
    {name: '箩', nameEn: 'GRS'},
    {name: '米', nameEn: 'METR'},
    {name: '件', nameEn: 'PC'},
    {name: '台', nameEn: 'PC'},
    {name: '块', nameEn: 'PC'},
    {name: '盒', nameEn: 'BOX'},
    {name: '张', nameEn: 'PC'},
    {name: '双', nameEn: 'PAIR'},
    {name: '辆', nameEn: 'PC'},
    {name: '吨', nameEn: 'TON'},
    {name: '公斤', nameEn: 'KG'},
    {name: '副', nameEn: 'PC'},
    {name: '桶', nameEn: 'BBL'},
    {name: '条', nameEn: 'ST'},
    {name: '叠', nameEn: 'STACK'},
]

const packUnits = [
    {name: '纸箱', nameEn: 'CTN'},
    {name: '木箱', nameEn: 'C/S'},
    {name: '袋', nameEn: 'BAG'},
    {name: '包', nameEn: 'BAL'},
    {name: '捆', nameEn: 'BUN'},
    {name: '桶', nameEn: 'DRU'},
    {name: '托盘', nameEn: 'PLT'},
    {name: '展示盒', nameEn: 'DBX'},
    {name: '散装', nameEn: 'BULK'},
]

module.exports = {units, packUnits}
